# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishtask',
            name='approval_by',
            field=models.CharField(max_length=100, null=True, verbose_name='\u5ba1\u6838\u4eba'),
        ),
        migrations.AlterField(
            model_name='publishtask',
            name='approval_time',
            field=models.DateTimeField(null=True, verbose_name='\u5ba1\u6838\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='publishtask',
            name='deploy_by',
            field=models.CharField(max_length=100, null=True, verbose_name='\u53d1\u5e03\u4eba'),
        ),
        migrations.AlterField(
            model_name='publishtask',
            name='deploy_time',
            field=models.DateTimeField(null=True, verbose_name='\u53d1\u5e03\u65f6\u95f4'),
        ),
    ]
