# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-11 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express', '0009_auto_20160808_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='apppublishtask',
            name='client_config_iosverremark',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='apppublishtask',
            name='courier_config_iosverremark',
            field=models.TextField(null=True),
        ),
    ]
