# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-25 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express', '0011_apppublishtask_env'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='\u9879\u76ee\u540d\u79f0')),
                ('git_url', models.CharField(max_length=200, verbose_name='Git\u5730\u5740')),
                ('git_branch', models.CharField(max_length=100, verbose_name='Git Branch')),
                ('env', models.CharField(max_length=100, verbose_name='\u53d1\u5e03\u73af\u5883')),
                ('is_full', models.CharField(max_length=100, verbose_name='\u662f\u5426\u5168\u91cf\u66f4\u65b0')),
                ('host', models.CharField(max_length=100, verbose_name='\u670d\u52a1\u5668IP')),
                ('src', models.CharField(max_length=200, verbose_name='\u6e90\u5730\u5740')),
                ('dest', models.CharField(max_length=200, verbose_name='\u90e8\u7f72\u8def\u5f84')),
                ('tomcat_num', models.CharField(max_length=10, verbose_name='Tomcat\u7f16\u53f7')),
                ('backup_dir', models.CharField(max_length=200, verbose_name='\u5907\u4efd\u8def\u5f84')),
            ],
        ),
    ]
