# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-30 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express', '0013_auto_20160830_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='code',
            field=models.CharField(default='', max_length=100, verbose_name='\u9879\u76ee\u7f16\u53f7'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='language_type',
            field=models.CharField(default='', max_length=100, verbose_name='\u5f00\u53d1\u8bed\u8a00'),
            preserve_default=False,
        ),
    ]
