# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-05 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express', '0014_auto_20160830_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='idc',
            field=models.CharField(default='', max_length=100, verbose_name='\u673a\u623f'),
            preserve_default=False,
        ),
    ]
