# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-06 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express', '0015_project_idc'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishtask',
            name='is_auto_deploy',
            field=models.CharField(max_length=100, null=True, verbose_name='\u662f\u5426\u81ea\u52a8\u53d1\u5e03'),
        ),
    ]
