# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-22 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express', '0016_publishtask_is_auto_deploy'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ignore_setup',
            field=models.TextField(default='', verbose_name='\u5ffd\u7565\u4e0a\u4f20\u6587\u4ef6'),
            preserve_default=False,
        ),
    ]
