# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-27 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express', '0017_project_ignore_setup'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishtask',
            name='idc',
            field=models.CharField(max_length=1000, null=True, verbose_name='\u53d1\u5e03\u7c7b\u578b'),
        ),
    ]
