# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-24 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express', '0019_publishtask_qa_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishtask',
            name='deploy_info',
            field=models.TextField(null=True, verbose_name='\u53d1\u5e03\u8fc7\u7a0b\u8f93\u51fa'),
        ),
        migrations.AddField(
            model_name='publishtask',
            name='deploy_progress',
            field=models.CharField(max_length=100, null=True, verbose_name='\u53d1\u5e03\u8fdb\u5ea6'),
        ),
    ]
