# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-04 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('express', '0021_publishtask_deploy_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishTaskDeploy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deploy_progress', models.CharField(max_length=100, null=True, verbose_name='\u53d1\u5e03\u8fdb\u5ea6')),
                ('deploy_total', models.CharField(max_length=100, null=True, verbose_name='\u53d1\u5e03\u6240\u9700\u6b65\u9aa4')),
                ('deploy_info', models.TextField(null=True, verbose_name='\u53d1\u5e03\u8fc7\u7a0b\u8f93\u51fa')),
            ],
        ),
        migrations.RemoveField(
            model_name='publishtask',
            name='deploy_info',
        ),
        migrations.RemoveField(
            model_name='publishtask',
            name='deploy_progress',
        ),
        migrations.RemoveField(
            model_name='publishtask',
            name='deploy_total',
        ),
        migrations.AddField(
            model_name='publishtaskdeploy',
            name='publishtask',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='express.PublishTask'),
        ),
    ]
