# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-12 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termlog',
            name='timestamp',
            field=models.IntegerField(default=1465724220),
        ),
    ]
