# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jlog', '0004_auto_20160628_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termlog',
            name='timestamp',
            field=models.IntegerField(default=1467336521),
        ),
    ]
