# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jlog', '0005_auto_20160701_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termlog',
            name='timestamp',
            field=models.IntegerField(default=1467686107),
        ),
    ]
