# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jlog', '0008_auto_20160705_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termlog',
            name='timestamp',
            field=models.IntegerField(default=1467686351),
        ),
    ]
