# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jlog', '0011_auto_20160711_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termlog',
            name='timestamp',
            field=models.IntegerField(default=1468230322),
        ),
    ]
