# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jlog', '0014_auto_20160712_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termlog',
            name='timestamp',
            field=models.IntegerField(default=1468907363),
        ),
    ]
