# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jlog', '0021_auto_20160727_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termlog',
            name='timestamp',
            field=models.IntegerField(default=1469607332),
        ),
    ]
