# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-30 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jlog', '0030_auto_20160830_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termlog',
            name='timestamp',
            field=models.IntegerField(default=1472559880),
        ),
    ]
