# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-22 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jlog', '0031_auto_20160830_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termlog',
            name='timestamp',
            field=models.IntegerField(default=1474533287),
        ),
    ]
