# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-27 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jlog', '0032_auto_20160922_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termlog',
            name='timestamp',
            field=models.IntegerField(default=1474963726),
        ),
    ]
