# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-24 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jlog', '0034_auto_20161017_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termlog',
            name='timestamp',
            field=models.IntegerField(default=1477295539),
        ),
    ]
