# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-25 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jlog', '0035_auto_20161024_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termlog',
            name='timestamp',
            field=models.IntegerField(default=1477382136),
        ),
    ]
