# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-25 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jlog', '0036_auto_20161025_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termlog',
            name='timestamp',
            field=models.IntegerField(default=1477382592),
        ),
    ]
