# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-02 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jlog', '0037_auto_20161025_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termlog',
            name='timestamp',
            field=models.IntegerField(default=1478053984),
        ),
    ]
