# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-04 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jlog', '0038_auto_20161102_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termlog',
            name='timestamp',
            field=models.IntegerField(default=1478230943),
        ),
    ]
