# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-04 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jlog', '0040_auto_20161104_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termlog',
            name='timestamp',
            field=models.IntegerField(default=1478244525),
        ),
    ]
